# Auto-generated by .github/workflows/release.yml on each tagged release.
# Do not edit by hand — changes are overwritten on the next release.
{
  version = "0.3.1";
  hashes = {
    "x86_64-linux" = "3f387efcd0f307e52447486d3e220c9d0a5093cd10a85e3eb0b6e6106ef091b1";
    "aarch64-linux" = "6a28ee27602983b7b6d6ef561121d12a5b337b8fd39219a60e5dbba028bf6a32";
    "x86_64-darwin" = "0eef5e4ed03660ab733b39501b8bcaf5fc147c9340e80a161f99dc3bd2083f9c";
    "aarch64-darwin" = "74043fecd87c1fe7611471d646a8e238cbf4f45fe06491e31f85af8c704a105f";
  };
}
