# Auto-generated by .github/workflows/release.yml on each tagged release.
# Do not edit by hand — changes are overwritten on the next release.
{
  version = "0.1.0";
  hashes = {
    "x86_64-linux" = "664608e4880d889948de4eedfb86330128389dea7a3b9146bc9b32f82cbff66b";
    "aarch64-linux" = "e6981979b51ee55a9a59d47a3baa04c93a5f6f352fc90a071785b9e51929c4b3";
    "x86_64-darwin" = "a20240986b46d13c2b7797155f89966049f381c4967be2f2803ee81132265eca";
    "aarch64-darwin" = "273eedb53a82746e64e28a3f710e467ed8c95222ae70b1591320dc321ce3fb2a";
  };
}
