# Auto-generated by .github/workflows/release.yml on each tagged release.
# Do not edit by hand — changes are overwritten on the next release.
{
  version = "0.1.0";
  hashes = {
    "x86_64-linux" = "a9489a1bb562492ecc64ee678efebbcd150c187576e73be2565218d341dd2c54";
    "aarch64-linux" = "49ce2d1f5042e74ea6dacbecc7f35ebf1a7e6d5e33f241b3c8d768e79eaa9ef6";
    "x86_64-darwin" = "cfe5c4d3e71351981a21709a3d53c8e1ffecdbf2da2a713063fb80447b4abbc3";
    "aarch64-darwin" = "69089f9e682a822b8e80c07c9bab893c3bcf91fd9fd307c94281be5145cc6230";
  };
}
