{
  description = "canarycode — a fast, minimal terminal coding agent (CanaryCode)";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs =
    { self, nixpkgs }:
    let
      # Version + per-system sha256 of the released binaries. Regenerated by the
      # release workflow on every tag (see .github/workflows/release.yml).
      release = import ./nix/release.nix;

      systems = [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      forAllSystems = nixpkgs.lib.genAttrs systems;

      # Map a Nix system to the matching release asset name.
      assetFor = {
        "x86_64-linux" = "canarycode-linux-x64";
        "aarch64-linux" = "canarycode-linux-arm64";
        "x86_64-darwin" = "canarycode-darwin-x64";
        "aarch64-darwin" = "canarycode-darwin-arm64";
      };

      canarycodeFor =
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          asset = assetFor.${system};
        in
        pkgs.stdenv.mkDerivation {
          pname = "canarycode";
          version = release.version;

          src = pkgs.fetchurl {
            url = "https://github.com/CanaryCoders/CanaryCodeCli/releases/download/v${release.version}/${asset}";
            sha256 = release.hashes.${system};
          };

          dontUnpack = true;

          nativeBuildInputs =
            [ pkgs.makeWrapper ]
            ++ pkgs.lib.optionals pkgs.stdenv.isLinux [ pkgs.autoPatchelfHook ];
          # The Bun-compiled binary links libc/libstdc++ on Linux; autoPatchelfHook
          # rewrites its interpreter and rpath. macOS binaries need no patching.
          buildInputs = pkgs.lib.optionals pkgs.stdenv.isLinux [ pkgs.stdenv.cc.cc.lib ];

          installPhase = ''
            runHook preInstall
            install -Dm755 "$src" "$out/bin/canarycode"
            runHook postInstall
          '';

          # Nix-managed installs are immutable — force self-update off so `canarycode`
          # never tries to overwrite the read-only store binary.
          postFixup = ''
            wrapProgram "$out/bin/canarycode" --set CANARYCODE_DISABLE_UPDATE 1
          '';

          meta = with pkgs.lib; {
            description = "A fast, minimal terminal coding agent";
            homepage = "https://github.com/CanaryCoders/CanaryCodeCli";
            mainProgram = "canarycode";
            platforms = systems;
          };
        };
    in
    {
      packages = forAllSystems (system: {
        default = canarycodeFor system;
        canarycode = canarycodeFor system;
      });

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${canarycodeFor system}/bin/canarycode";
        };
      });

      # Home Manager module: `programs.canarycode.enable = true;` (+ optional `settings`).
      homeManagerModules.default = import ./nix/hm-module.nix self;
      homeManagerModules.canarycode = self.homeManagerModules.default;

      formatter = forAllSystems (
        system: nixpkgs.legacyPackages.${system}.nixfmt-rfc-style
      );
    };
}
